### ISSUE TITLE
GuzzleHttp and Let's Encrypt

### ISSUE THREAD

**Issue by BenjaminP7** [vinkas0/discourse-php#3]
Having an error with GuzzleHttp : 

> Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' 

wich refer to : 

> CURLE_SSL_CACERT (60)
> Peer certificate cannot be authenticated with known CA certificates.

Since let's encrypt is young I get why it's not supported as know CA certificates, but it's the default SSL Discourse is ship with and it's free :/

Any idea ?

**Comment by vinothkannans** [comment]
since this issue not directly related to the code I just moved it in our Discourse forum https://codiss.com/t/guzzlehttp-and-lets-encrypt/27
